WITH source AS(
    SELECT * FROM {{ source('shopify_raw', '"ORDER"') }}
)
SELECT id,
    order_number,
    financial_status,
    fulfillment_status,
    created_at,
    processed_at,
    updated_at,
    cancelled_at,
    cancelled_at,
    shipping_address_address_1,
    shipping_address_address_2,
    shipping_address_city,
    shipping_address_province_code,
    shipping_address_zip,
    shipping_address_first_name,
    shipping_address_last_name,
    shipping_address_name,
    shipping_address_latitude,
    shipping_address_longitude,
    billing_address_address_1,
    billing_address_address_2,
    billing_address_city,
    billing_address_province_code,
    billing_address_zip,
    billing_address_first_name,
    billing_address_last_name,
    billing_address_name,
    billing_address_latitude,
    billing_address_longitude,
    customer_id,
    user_id,
    checkout_id,
    referring_site,
    app_id,
    REGEXP_SUBSTR(note_attributes, '"name"\s*:\s*"BrandAmbassadorID"\s*,\s*"order_id"\s*:\s*null\s*,\s*"value"\s*:\s*"([^"]*)"', 1, 1, 'i', 1) AS BrandAmbassadorID,
    REGEXP_SUBSTR(note_attributes, '"name"\s*:\s*"PartyID"\s*,\s*"order_id"\s*:\s*null\s*,\s*"value"\s*:\s*"([^"]*)"', 1, 1, 'i', 1) AS PartyID,
    REGEXP_SUBSTR(note_attributes, '"name"\s*:\s*"HostID"\s*,\s*"order_id"\s*:\s*null\s*,\s*"value"\s*:\s*"([^"]*)"', 1, 1, 'i', 1) AS HostID,
    REGEXP_SUBSTR(note_attributes, '"name"\s*:\s*"dateOfBirth"\s*,\s*"order_id"\s*:\s*null\s*,\s*"value"\s*:\s*"([^"]*)"', 1, 1, 'i', 1) AS DateOfBirth,
    note_attributes,
    --Edit the splits once I find out more information on how notes/comments are inputted
    SPLIT_PART(SPLIT_PART(note, '\n', 2), ':', 2) AS Sphere_Order_Number,
    SPLIT_PART(SPLIT_PART(note, '\n', 3), ':', 2) AS Infotrax_Order_Number,
    _fivetran_deleted,
    _fivetran_synced
FROM source